trigger-CI:
  tags:
    - package-CI
  variables:
    PACKAGE: filesystem
    REPO: core
    SOURCE: ""
  script:
    - '[[ ! -d package/CI ]] && git clone git@github.com:manjaro/package-CI.git'
    - cd package-CI/.github/workflows
    - git pull
    - 'sed -i -e "s/package:.*/package: $PACKAGE/" build-package.yml'
    - 'sed -i -e "s/ repo:.*/ repo: $REPO/" build-package.yml'
    - 'sed -i -e "s/source:.*/source: $SOURCE/" build-package.yml'
    - 'sed -i -e "s/# built.*/# built $(date)/" build-package.yml'
    - git add build-package.yml
    - 'git commit -m"build $PACKAGE"'
    - git push
